# Generated by Django 2.0.5 on 2018-05-16 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AcessRecord',
            new_name='AccessRecord',
        ),
    ]
